# Generated by Django 3.0.8 on 2020-08-07 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps_vis', '0003_entry_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='latitude',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='longitude',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
